/**
 * Project Scaffolding Tool (Phase 7.1)
 *
 * project_init creates a starter project structure for one of:
 *   - react       (Vite + React + TypeScript)
 *   - nextjs      (Next.js 14 + TypeScript)
 *   - node        (Node.js Express API)
 *   - python      (Python Flask API)
 *   - static      (HTML + CSS + JS)
 *
 * All file I/O uses fs/promises for non-blocking performance.
 */

import fsp from 'fs/promises';
import path from 'path';
import logger from '../../utils/logger.js';

const SANDBOX = process.env.SANDBOX_WORKSPACE || './sandbox-workspace';

// ============================================================================
// PROJECT TEMPLATES
// ============================================================================

const templates = {
  react: {
    files: {
      'package.json': `{
  "name": "react-app",
  "private": true,
  "version": "0.0.1",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  },
  "devDependencies": {
    "@vitejs/plugin-react": "^4.3.0",
    "typescript": "^5.5.0",
    "vite": "^5.4.0"
  }
}
`,
      'vite.config.ts': `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  server: { port: 3000 }
});
`,
      'tsconfig.json': `{
  "compilerOptions": {
    "target": "ES2022",
    "lib": ["ES2022", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "jsx": "react-jsx",
    "strict": true
  },
  "include": ["src"]
}
`,
      'index.html': `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>React App</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`,
      'src/main.tsx': `import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
`,
      'src/App.tsx': `import { useState } from 'react';

export default function App() {
  const [count, setCount] = useState(0);
  return (
    <div style={{ fontFamily: 'sans-serif', padding: '2rem', textAlign: 'center' }}>
      <h1>Hello from React + Vite</h1>
      <button onClick={() => setCount(c => c + 1)}>Count: {count}</button>
    </div>
  );
}
`,
      'README.md': `# React App (Vite + TypeScript)

## Get Started
\`\`\`bash
npm install
npm run dev
\`\`\`

The app runs on http://localhost:3000
`
    }
  },

  nextjs: {
    files: {
      'package.json': `{
  "name": "nextjs-app",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "^14.2.0",
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  },
  "devDependencies": {
    "typescript": "^5.5.0",
    "@types/node": "^20.14.0",
    "@types/react": "^18.3.0",
    "@types/react-dom": "^18.3.0"
  }
}
`,
      'tsconfig.json': `{
  "compilerOptions": {
    "target": "ES2022",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
`,
      'next.config.js': `/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true
};

module.exports = nextConfig;
`,
      'app/layout.tsx': `import './globals.css';
import { ReactNode } from 'react';

export const metadata = {
  title: 'Next.js App',
  description: 'Generated by MAX'
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`,
      'app/page.tsx': `export default function Home() {
  return (
    <main style={{ fontFamily: 'sans-serif', padding: '2rem', textAlign: 'center' }}>
      <h1>Hello from Next.js 14</h1>
      <p>Edit app/page.tsx and save to reload.</p>
    </main>
  );
}
`,
      'app/globals.css': `* { box-sizing: border-box; }
html, body { margin: 0; padding: 0; background: #fff; color: #111; }
`,
      'README.md': `# Next.js 14 App

## Get Started
\`\`\`bash
npm install
npm run dev
\`\`\`

Open http://localhost:3000
`
    }
  },

  node: {
    files: {
      'package.json': `{
  "name": "node-api",
  "version": "0.0.1",
  "type": "module",
  "main": "index.js",
  "scripts": {
    "start": "node index.js",
    "dev": "node --watch index.js"
  },
  "dependencies": {
    "express": "^5.0.0",
    "cors": "^2.8.5"
  }
}
`,
      'index.js': `import express from 'express';
import cors from 'cors';

const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());

app.get('/health', (req, res) => {
  res.json({ status: 'ok', timestamp: Date.now() });
});

app.get('/', (req, res) => {
  res.json({ message: 'Hello from Node.js API', endpoints: ['/health', '/users'] });
});

app.get('/users', (req, res) => {
  res.json([{ id: 1, name: 'Alice' }, { id: 2, name: 'Bob' }]);
});

app.listen(PORT, () => {
  console.log(\`API running on http://localhost:\${PORT}\`);
});
`,
      '.env.example': `PORT=3000
NODE_ENV=development
`,
      'README.md': `# Node.js API (Express)

## Get Started
\`\`\`bash
npm install
npm run dev
\`\`\`

The API runs on http://localhost:3000

## Endpoints
- GET /         — service info
- GET /health   — health check
- GET /users    — sample users
`
    }
  },

  python: {
    files: {
      'requirements.txt': `flask==3.0.0
flask-cors==4.0.0
gunicorn==21.2.0
`,
      'app.py': `from flask import Flask, jsonify, request
from flask_cors import CORS

app = Flask(__name__)
CORS(app)

@app.route('/')
def index():
    return jsonify({
        'message': 'Hello from Flask',
        'endpoints': ['/health', '/users']
    })

@app.route('/health')
def health():
    return jsonify({'status': 'ok'})

@app.route('/users')
def users():
    return jsonify([
        {'id': 1, 'name': 'Alice'},
        {'id': 2, 'name': 'Bob'}
    ])

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=True)
`,
      '.env.example': `FLASK_ENV=development
FLASK_PORT=5000
`,
      'README.md': `# Python API (Flask)

## Get Started
\`\`\`bash
pip install -r requirements.txt
python app.py
\`\`\`

The API runs on http://localhost:5000

## Endpoints
- GET /         — service info
- GET /health   — health check
- GET /users    — sample users
`
    }
  },

  static: {
    files: {
      'index.html': `<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Static Site</title>
  <link rel="stylesheet" href="styles.css" />
</head>
<body>
  <main>
    <h1>Hello, World</h1>
    <p>Edit <code>index.html</code>, <code>styles.css</code>, and <code>script.js</code> to build your site.</p>
    <button id="btn">Click me</button>
    <p id="count">0 clicks</p>
  </main>
  <script src="script.js"></script>
</body>
</html>
`,
      'styles.css': `* { box-sizing: border-box; }
html, body {
  margin: 0;
  padding: 0;
  font-family: system-ui, -apple-system, sans-serif;
  background: #f5f5f5;
  color: #111;
}
main {
  max-width: 720px;
  margin: 4rem auto;
  padding: 2rem;
  background: #fff;
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);
  text-align: center;
}
button {
  background: #0070f3;
  color: #fff;
  border: none;
  padding: 0.6rem 1.2rem;
  border-radius: 4px;
  cursor: pointer;
  font-size: 1rem;
}
button:hover { background: #005bb5; }
code { background: #eee; padding: 2px 6px; border-radius: 3px; }
`,
      'script.js': `let count = 0;
const btn = document.getElementById('btn');
const display = document.getElementById('count');

btn.addEventListener('click', () => {
  count++;
  display.textContent = \`\${count} click\${count === 1 ? '' : 's'}\`;
});
`,
      'README.md': `# Static Site

A simple HTML + CSS + JS starter.

## Get Started
Open \`index.html\` in your browser, or serve the folder with any static server:

\`\`\`bash
npx serve .
\`\`\`
`
    }
  }
};

// ============================================================================
// TOOL DEFINITIONS
// ============================================================================

export const projectTools = {
  project_init: {
    name: 'project_init',
    description: 'Initialize a new project structure with starter files for one of: react, nextjs, node, python, static. Creates package.json/requirements.txt, entry files, and basic config. Use this when the user asks to "create a project", "scaffold a new app", or "set up a [template] project".',
    params: {
      template: 'string (required) — one of: react, nextjs, node, python, static',
      dir: 'string (optional) — subdirectory to create the project in (default: project name based on template)'
    },
    execute: async (args) => {
      const template = String(args.template || '').toLowerCase().trim();
      const dir = args.dir || `${template}-app`;

      if (!template) {
        return `Error: template is required. Available templates: ${Object.keys(templates).join(', ')}`;
      }

      const tpl = templates[template];
      if (!tpl) {
        return `Error: unknown template "${template}". Available: ${Object.keys(templates).join(', ')}`;
      }

      const projectRoot = path.resolve(SANDBOX, dir);
      if (!projectRoot.startsWith(path.resolve(SANDBOX))) {
        return 'Error: project dir is outside the sandbox workspace';
      }

      try {
        // Create project root
        await fsp.mkdir(projectRoot, { recursive: true });

        // Write each file in the template
        const written = [];
        for (const [relPath, content] of Object.entries(tpl.files)) {
          const fullPath = path.join(projectRoot, relPath);
          await fsp.mkdir(path.dirname(fullPath), { recursive: true });
          await fsp.writeFile(fullPath, content, 'utf-8');
          written.push(relPath);
        }

        logger.info('TOOL:project_init', { template, dir, files: written.length });

        return `Created ${template} project in ${dir}/\n` +
          `Files created (${written.length}):\n` +
          written.map(f => `  - ${dir}/${f}`).join('\n') +
          `\n\nNext steps:\n` +
          (template === 'python'
            ? `  cd ${dir} && pip install -r requirements.txt && python app.py`
            : `  cd ${dir} && npm install && npm run dev`);
      } catch (err) {
        return `Error creating project: ${err.message}`;
      }
    }
  }
};

export default projectTools;
